tensorboard_dir_name = 'MR_f_RND_vid_e7_0.99'
env_name = "MontezumaRevengeNoFrameskip-v4"
env_alias = "MR_f"
max_frames = 30 * 60 * 60
dueling = 1
grad_norm = 10
model_copy = 1500
lr = 1e-4
per_size = 1e6
per_alpha = 0.7
per_beta = 0.5
per_beta_steps = 1e7
per_num_steps = 1
max_steps = int(1e9)
BS = 32
epsilon_min = 0.02
epsilon_max = 1
explorer_method = 0  # 0 means linear schedule, 1 means random selection NOTE MODIFY EPSILON_MIN AND MAX
epsilon_steps = 1e7
epsilon_num = 256
epsilon_interval = 2000
warmup = 10000
discount = 0.99
update_interval = 4
RND_reward = 1
video_every = 2e2
rnd_beta = 0.5