tensorboard_dir_name = 'RND_random_epsilon'
env_name = "MontezumaRevengeNoFrameskip-v4"
max_frames = 30 * 60 * 60
dueling = 1
grad_norm = 10
model_copy = 1500
lr = 1e-4
per_size = 1e6
per_alpha = 0.6
per_beta = 0.4
per_beta_steps = 1e7
per_num_steps = 1
episodes = int(1e5)
max_steps = int(1e9)
BS = 32
epsilon_min = 0.02
epsilon_max = 0.7
explorer_method = 1  # 0 means linear schedule, 1 means random selection NOTE MODIFY EPSILON_MIN AND MAX
epsilon_steps = 5e6
epsilon_num = 256
epsilon_interval = 2000
warmup = 10000
discount = 0.99
update_interval = 4
RND_reward = 1